name: my First Robot Check

on:
  push:
    branches:
      - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Say Hello
      run: echo "hello, i am your first robot Github Actions!"
